route:
    receiver: 'slack'
 
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'alertmanager'
            channel: '#monitoring-instances'
            api_url: 'https://hooks.slack.com/services/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'