global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://hooks.slack.com/services/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'
          send_resolved: false