route:
    receiver: 'slack'
 
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'BrunoSantos'
            channel: '#monitoring-instances'
            api_url: 'https://hooks.slack.com/services/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'