global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-instances'
    send_resolved: true