version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node-exporter
    network_mode: "host"

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    network_mode: "host"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    network_mode: "host"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - "8081:8080"
    network_mode: "host"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  
  goapp:
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: golangapp
    ports:
      - "8090:8090"
    network_mode: "host"
    
  geoip:
    build:
      context: .
      dockerfile: dockerfile
    container_name: geoipexporter
    ports:
      - "9300:9300"
    network_mode: "host"

