version: '3'

services:
  meu-app-go:
    build:
      context: .
    ports:
      - "8090:8090"
    depends_on:
      - jaeger
    network_mode: host

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
    network_mode: host

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - meu-app-go
      - node-exporter
    network_mode: host

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    network_mode: host

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    depends_on:
      - meu-app-go
    network_mode: host

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    network_mode: host