version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - node-exporter
    network_mode: "host"

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    network_mode: "host"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    network_mode: "host"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    network_mode: "host"
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  
  app-server1:
    build:
      context: .
      dockerfile: goapp/dockerfile
    container_name: webgoapp
    ports:
      - "8090:8090"
    network_mode: "host"

  app-server2:
    image: webgoapp
    container_name: webgoapp
    ports:
      - "8090:8090"
    network_mode: "host"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app-server1
      - app-server2

  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  web-app:
    image: webgoapp
    container_name: web-app
    labels:
      - "traefik.http.routers.web-app.rule=Host(`localhost/ping`)"
      - "traefik.http.routers.web-app.entrypoints=web"
      - "traefik.http.routers.web-app.middlewares=redirect-to-https"
      - "traefik.http.routers.web-app-secure.rule=Host(`localhost`)"
      - "traefik.http.routers.web-app-secure.entrypoints=websecure"
      - "traefik.http.routers.web-app-secure.tls=true"
      - "traefik.http.routers.web-app-secure.tls.certresolver=myresolver"
    networks:
      - host
    depends_on:
      - traefik

networks:
  web:
    external: true