global:
  scrape_interval: 5s
  external_labels:
    monitor: 'docker-container-monitor'

rule_files:
  - "/etc/prometheus/alert.rules.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8080']
  - job_name: simple_server
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8090"]
  - job_name: 'Jenkins'
    metrics_path: /prometheus
    scheme: http
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['jenkins:8080']
    basic_auth:
      username: 'admin'
      password: 'admin'
 
