global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"
  
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
  - job_name: simple_server
    static_configs:
      - targets: ["localhost:8090"]
