FROM golang:1.18
WORKDIR /go/src/app
COPY . .
RUN go get -u github.com/opentracing/opentracing-go
RUN go get -u github.com/uber/jaeger-client-go
RUN go mod init prom_example
RUN go mod tidy
RUN go build server.go
CMD ["./server"] 
EXPOSE 8090
