global:
  scrape_interval: 5s
  
scrape_configs:
  - job_name: simple_server
    static_configs:
      - targets: ["localhost:8090"]
  - job_name: 'GeoIPExporter'
    static_configs:
      - targets: ['localhost:9300']
