FROM golang:1.18 AS build
WORKDIR /go/src/app
COPY . .
RUN go get -u github.com/gin-gonic/gin
RUN CGO_ENABLED=0 GOOS=linux go build -o server .
FROM alpine:latest
WORKDIR /app
COPY --from=build /go/src/app/server .
EXPOSE 80
CMD ["./server"]